### ISSUE TITLE
Linux 4.15.0: modpost: Found 1 section mismatch(es)

### ISSUE THREAD

**Issue by c0d3z3r0** [iksaif/thinkpad-wmi#3]
Linux 4.15.0

make -C drivers/platform/x86 default
make[1]: Entering directory '/home/c0d3/src/_cust/thinkpad_wmi-dkms/thinkpad-wmi/drivers/platform/x86'
make -C /lib/modules/4.15.0-1-c0/build SUBDIRS=/home/c0d3/src/_cust/thinkpad_wmi-dkms/thinkpad-wmi/drivers/platform/x86 thinkpad-wmi.ko
make[2]: Entering directory '/usr/lib/modules/4.15.0-1-c0/build'
  MODPOST 1 modules
WARNING: modpost: Found 1 section mismatch(es).
To see full details build your kernel with:
'make CONFIG_DEBUG_SECTION_MISMATCH=y'
make[2]: Leaving directory '/usr/lib/modules/4.15.0-1-c0/build'
make[1]: Leaving directory '/home/c0d3/src/_cust/thinkpad_wmi-dkms/thinkpad-wmi/drivers/platform/x86'

**Comment by c0d3z3r0** [comment]
#4

**Comment by iksaif** [comment]
Thanks !
